### PR TITLE
Fix the `impure` option

### LINKED ISSUE #1063: `impure` option breaks `devenv up`
**Describe the bug**

If you add `impure: true` to `devenv.yaml`, that option is passed to `nix-store` when adding the GC root. `nix-store` does not have such an option.

```
❯ devenv up                                                                                               │~
• Building processes ...                                                                                  │~
error:                                                                                                    │~
       error: unknown flag '--impure'                                                                     │~
Try '/nix/store/41qs712gwygmsjk8ns2yclyxpgalx4hi-nix-devenv-2.21.0pre20240315_c5bbf14/bin/nix-store --help│~
' for more information.                                                                                   │~
                                                                                                          │~
✖ Command produced the following output:                                                                  │~
                                                                                                          │~
                                                                                                          │~
✔ Building processes in 4.6s.                                                                             │~
Error:   × Command `/nix/store/41qs712gwygmsjk8ns2yclyxpgalx4hi-nix-devenv-2.21.0pre20240315_c5bbf14/bin/n│~
ix-                                                                                                       │~
  │ store --show-trace --extra-experimental-features nix-command --extra-experimental-features flakes     │~
  │ --option warn-dirty false --option eval-cache false --keep-going --max-jobs 4 --add-root /home/       │~
  │ sandydoo/code/test/.devenv/gc/procfilescript -r /nix/store/ncvaji28sl14qylr25madjrzmjiywss3-devenv-   │~
  │ up --impure` failed with with exit code 1
```

**To reproduce**

`devenv.yaml`

```nix
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling

impure: true
```

**Version**
 
```
❯ devenv version
devenv 1.0.2 (aarch64-linux)
```

### PR DESCRIPTION
**Pull request by sandydoo**
Fixes #1063.

### CODE REVIEW

File: devenv/src/command.rs [hunk 1]
```diff
@@ -140,7 +140,9 @@ impl App {
             };
 
             if self.cli.impure || self.config.impure {
-                flags.push("--impure");
+                if !command.starts_with("nix-store") {
```
Comment (domenkozar) [inline devenv/src/command.rs:143]: maybe we should instead allow it only when `nix develop`?

Comment (sandydoo) [reply devenv/src/command.rs:143]: Maybe? Do any of the `build` or `eval` commands need impure?

Comment (domenkozar) [reply devenv/src/command.rs:143]: yeah, maybe we should do it when `command.ends_with("nix")`

Comment (sandydoo) [reply devenv/src/command.rs:143]: or `command == "nix"` at that point?
