### PR TITLE
devenv: fix the cachix integration

### LINKED ISSUE #1311: Crash because of missing file
**Describe the bug**

After setting up a simple devenv and setting `CACHIX_AUTH_TOKEN`, `devenv test` fails with very little explanation.

**To reproduce**

[Gist](https://gist.github.com/l0b0/21f5f56c074b7a3d2732779dbfc7c1a7)

**Version**
 
devenv 1.0.7 (x86_64-linux)

Using flakes.

### PR DESCRIPTION
**Pull request by sandydoo**
Fixes the `cachix watch-exec` command. 
Also pretty-prints the command if `run_nix` fails to make it easier to track down which command is failing in the future.

Fixes #1311.

### CODE REVIEW

File: devenv/src/command.rs [hunk 1]
```diff
@@ -58,23 +58,21 @@ impl Devenv {
...
-            let result = if options.logging {
+            if options.logging {
                 cmd.stdin(std::process::Stdio::inherit())
-                    .stderr(std::process::Stdio::inherit())
-                    .output()
-                    .expect("Failed to run command")
-            } else {
-                cmd.output().expect("Failed to run command")
-            };
+                    .stderr(std::process::Stdio::inherit());
```
Comment (domenkozar) [inline devenv/src/command.rs:68]: I'm not sure this works well with `devenv print-dev-env`?

Comment (sandydoo) [reply devenv/src/command.rs:68]: what do you mean? this part is functionally the same as before.

**Comment by l0b0** [comment]
Any timeline on this will be released?

**Comment by domenkozar** [comment]
Thanks for the ping: https://github.com/NixOS/nixpkgs/pull/329479
